name: ayagrubmi
#   # Nazwa projektu
#   name: ayagrubmi
description: A simple calculator for calculating body mass index (BMI)

#   
#   # Opis projektu
#   description: "A simple calculator for calculating body mass index (BMI)"
#   


publish_to: 'none' 

#   # Brak publikacji na pub.dev
#   publish_to: "none"
#   

version: 1.0.0+1

#   # Wersja projektu
#   version: 1.0.0+1
#   


environment:
  sdk: ">=2.12.0 <3.0.0"

#   # Środowisko
#   environment:
#     sdk: ">=2.12.0 <3.0.0"
#   


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
#     cupertino_icons: ^1.0.6

  flutter_spinkit: ^5.1.0
#     flutter_spinkit: ^5.1.0


  firebase_auth: ^4.19.3
#     firebase_auth: ^4.19.2

  cloud_firestore: ^4.17.1
#     cloud_firestore: ^4.17.0

  provider: ^6.0.2
#     provider: ^6.0.2

  #google_fonts: ^4.0.3
#     google_fonts: 4.0.3

  flutter_keyboard_visibility: ^6.0.0
#     flutter_keyboard_visibility: ^6.0.0

  #flutterflow_ui: ^0.2.0+1
#     flutterflow_ui: ^0.2.0+1

  http: ^1.2.1


#   # Zależności
#   dependencies:
#     flutter:
#       sdk: flutter
#     http: 0.13.6
#     firebase_auth: ^4.19.2
#     #flutter_macos: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

#   # Zależności deweloperskie
#   dev_dependencies:
#     flutter_test:
#       sdk: flutter
#     flutter_lints: ^3.0.0
#     flutter_launcher_icons: ^0.13.1
#     build_runner: ^2.4.9

flutter:
  uses-material-design: true

#   # Konfiguracja Flutter
#   flutter:
#     uses-material-design: true
#   
  
assets:
  - assets/grubmi_logo.png
  - assets/trolface.png

#   assets:
#     - assets/grubmi_logo.png
#     - assets/trolface.png
#   


flutter_icons:
  android: true
  ios: true
  image_path: "assets/grubmi_logo.png"


#   flutter_icons:
#     android: true
#     ios: true
#     image_path: "assets/grubmi_logo.png"
#    


